services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    # Map host port 8000 to internal container port 5000
    ports:
      - "8000:5000" 
    
    volumes:
      - ./instance:/app/instance
    
    # Inject all environment variables here:
    environment:
      # Flask variables (FLASK_APP is crucial for Flask to run app.py)
      - FLASK_APP=app.py
      - FLASK_ENV=development # Enables debug mode
      - SECRET_KEY=a_very_secret_key_that_you_should_change_for_production
      
      # Custom API Keys
      - ORCHESTRATOR_API_KEY_PROVIDERS=supersecretproviderkey123
      - ORCHESTRATOR_API_KEY_CONSUMERS=ultrasecretconsumerkey456
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  provider:
    build:
      context: ./provider_agent
      dockerfile: Dockerfile
    
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      orchestrator:
        condition: service_healthy
              
    environment:
    - DATABASE_URL=postgresql://... # Your Neon URL
    - ORCHESTRATOR_API_KEY_PROVIDERS=matcha-beta-2026
    - ORCHESTRATOR_API_KEY_CONSUMERS=ultrasecretconsumerkey456
