services:
  - type: web
    name: matcha-orchestrator
    plan: free
    runtime: docker
    dockerfilePath: ./orchestrator/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false # This tells Render NOT to overwrite this if it exists
      - key: ORCHESTRATOR_API_KEY_PROVIDERS
        sync: false
      - key: ORCHESTRATOR_API_KEY_CONSUMERS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_PUBLIC_DOMAIN
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false